### ISSUE TITLE
Create a new test environment in AWS

### ISSUE THREAD

**Issue by anacalderonmx** [AnanseGroup/atlas_of_innovation#96]
52.37.166.83

**Comment by annawb** [comment]
@Rojo and @anacalderonmx -- change of plans! We decided to transfer the AWS to Nation of Makers, since they've already got a large server that's fully-funded (including maintenance costs) for a number of years. So I'm closing this issue and handing the task over to Nirupama at Nation of Makers instead. Apologies for the late notice, and I'm very sorry if you've already been working on this AWS transfer.

**Comment by Rojo** [comment]
Meanwhile, the IP for the `Test` env we will be using until the access for the new architecture is ready is [52.37.166.83](52.37.166.83).
