### ISSUE TITLE
Create deployment Environment on Nation of Makers server

### ISSUE THREAD

**Issue by anacalderonmx** [AnanseGroup/atlas_of_innovation#97]
This is similar with the test environment but with a full elastic beanstalk deploy.

**Comment by annawb** [comment]
@Rojo and @anacalderonmx -- change of plans! We decided to transfer the AWS to Nation of Makers, since they've already got a large server that's fully-funded (including maintenance costs) for a number of years. So I'm closing this issue and handing the task over to Nirupama at Nation of Makers instead. Apologies for the late notice, and I'm very sorry if you've already been working on this task.

**Comment by annawb** [comment]
Actually, re-opening this with @Lyla-Fischer so we can hopefully add Nirupama to this Issues party and make sure that everyone has the right permissions...

**Comment by ParthenonTech** [comment]
Looking forward to the meeting tomorrow to discuss issues but at the moment it would appear that we will need to have this on a Linux server so the NoM server may not work for the project.  More info after tomorrow's meeting.

**Comment by Rojo** [comment]
For simpleness sake, we ditched AWS Beanstalk and used a basic CVS aproach with Git.
